apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskpro-deployment
  labels:
    app: taskpro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskpro
  template:
    metadata:
      labels:
        app: taskpro
    spec:
      containers:
        - name: taskpro
          image: devopsproject1.azurecr.io/taskpro:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: taskpro-service
  labels:
    app: taskpro
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: taskpro
